### ISSUE TITLE
批量转换之后，就只是汪汪汪三声是怎么回事呢？

### ISSUE THREAD

**Issue by GD2021** [LokerL/tts-vue#10]
#### Describe the bug
大佬，就是我在批量转换的时候，导入文本，然后生成下载，生成的mp3音频全部都是汪汪汪的声音。

**Comment by LokerL** [comment]
![image](https://user-images.githubusercontent.com/44148627/184817696-676d043c-d2ce-4903-9629-c5f926997c3f.png)
不理解，感觉有些匪夷所思。。。

**Comment by eatWh** [comment]
不是作者的事，微软那个接口只允许utf-8，其他编码的文本都会变成1，英文读起来就是one，连着就是汪汪汪了
