### ISSUE TITLE
我的软件莫名的出现了打不开的现象

### ISSUE THREAD

**Issue by yanjingtan** [LokerL/tts-vue#100]
在打开以后开始闪退，无法进入主界面。

**Comment by LokerL** [comment]
应该是配置文件改的有问题。

但是最近微软好像关闭了免费的接口，软件暂时不能用，打开也没用了。

**Comment by LokerL** [comment]
源代码已更新。预计2小时后上线安装包。版本号1.9.0。 @yanjingtan
