### ISSUE TITLE
已无法使用，微软又更新什么了？做等tts-vue更新！！！！

### ISSUE THREAD

**Issue by zxpyld3x** [LokerL/tts-vue#101]
已无法使用，微软又更新什么了？做等tts-vue更新！！！！

**Comment by LokerL** [comment]
微软好像关闭了免费的接口

**Comment by CHEN6311** [comment]
> 微软好像关闭了免费的接口

我有别的软件能用微软语音服务，还不会出现网络问题，但是联系作者（tts-vue）想发给她看看，作者并没有回复我，我还给他进行了微信转载试图联系他

**Comment by LokerL** [comment]
> > 微软好像关闭了免费的接口
> 
> 我有别的软件能用微软语音服务，还不会出现网络问题，但是联系作者（tts-vue）想发给她看看，作者并没有回复我，我还给他进行了微信转载试图联系他

我就是作者。。。
其他产品的可以用有两种可能：（个人猜测，不太准确）
1. 使用了edge浏览器的大声朗读接口
2. 使用了其他未知的ms-tts接口

**Comment by CHEN6311** [comment]
能否加我个联系方式，我把我最近使用微软语音工具的软件发给你，你看看，修改一下你的软件？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月7日(周五) 下午4:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LokerL/tts-vue] 已无法使用，微软又更新什么了？做等tts-vue更新！！！！ (Issue #101)




   
微软好像关闭了免费的接口
  
我有别的软件能用微软语音服务，还不会出现网络问题，但是联系作者（tts-vue）想发给她看看，作者并没有回复我，我还给他进行了微信转载试图联系他
  
我就是作者。。。
 其他产品的可以用有两种可能：（个人猜测，不太准确）
  
使用了edge浏览器的大声朗读接口 

使用了其他未知的ms-tts接口

**Comment by CHEN6311** [comment]
> > > 微软好像关闭了免费的接口
> > 
> > 
> > 我有别的软件能用微软语音服务,还不会出现网络问题,但是联系作者(tts-vue)想发给她看看,作者并没有回复我,我还给他进行了微信转载试图联系他
> 
> 我就是作者。。。其他产品的可以用有两种可能:(个人猜测,不太准确)
> 
> 1. 使用了边缘浏览器的大声朗读接口
> 2. 使用了其他未知的质谱-tts接口

我把我最近使用的软件发给你，你看看修改一下的软件呗。我还是觉得你做的更好用

**Comment by LokerL** [comment]
> > > > 微软好像关闭了免费的接口
> > > 
> > > 
> > > 我有别的软件能用微软语音服务,还不会出现网络问题,但是联系作者(tts-vue)想发给她看看,作者并没有回复我,我还给他进行了微信转载试图联系他
> > 
> > 
> > 我就是作者。。。其他产品的可以用有两种可能:(个人猜测,不太准确)
> > 
> > 1. 使用了边缘浏览器的大声朗读接口
> > 2. 使用了其他未知的质谱-tts接口
> 
> 我把我最近使用的软件发给你，你看看修改一下的软件呗。我还是觉得你做的更好用

谢谢，但是我不需要其他软件，我知道edge的接口，但是没时间修改。

**Comment by CHEN6311** [comment]
> > > > > 微软好像关闭了免费的接口
> > > > 
> > > > 
> > > > 我有别的软件能用微软语音服务,还不会出现网络问题,但是联系作者(tts-vue)想发给她看看,作者并没有回复我,我还给他进行了微信转载试图联系他
> > > 
> > > 
> > > 我就是作者。。。其他产品的可以用有两种可能:(个人猜测,不太准确)
> > > 
> > > 1. 使用了边缘浏览器的大声朗读接口
> > > 2. 使用了其他未知的质谱-tts接口
> > 
> > 
> > 我把我最近使用的软件发给你,你看看修改一下的软件呗。我还是觉得你做的更好用
> 
> 谢谢,但是我不需要其他软件,我知道边缘的接口,但是没时间修改。

微软浏览器是一个接口，但是主流用的语音人物不多

**Comment by CHEN6311** [comment]
> 

可惜我不会做，不然我就自己整个了

**Comment by CHEN6311** [comment]
> > > > > 微软好像关闭了免费的接口
> > > > 
> > > > 
> > > > 我有别的软件能用微软语音服务,还不会出现网络问题,但是联系作者(tts-vue)想发给她看看,作者并没有回复我,我还给他进行了微信转载试图联系他
> > > 
> > > 
> > > 我就是作者。。。其他产品的可以用有两种可能:(个人猜测,不太准确)
> > > 
> > > 1. 使用了边缘浏览器的大声朗读接口
> > > 2. 使用了其他未知的质谱-tts接口
> > 
> > 
> > 我把我最近使用的软件发给你,你看看修改一下的软件呗。我还是觉得你做的更好用
> 
> 谢谢,但是我不需要其他软件,我知道边缘的接口,但是没时间修改。

可以我不会弄，不然我就自己弄个了

**Comment by 0000duck** [comment]
https://speech.microsoft.com/audiocontentcreation   新的接口在这里

**Comment by CHEN6311** [comment]
你是怎么发现的，我从上个月，月底微软官网关了，我找到现在都没找到新的入口



---原始邮件---
发件人: "Ten Years A ***@***.***&gt;
发送时间: 2023年4月8日(周六) 晚上7:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LokerL/tts-vue] 已无法使用，微软又更新什么了？做等tts-vue更新！！！！ (Issue #101)




 
https://speech.microsoft.com/audiocontentcreation   新的接口在这里

**Comment by LokerL** [comment]
> https://speech.microsoft.com/audiocontentcreation 新的接口在这里

这个我也知道，这个用起来感觉还不如edge的接口

**Comment by 0000duck** [comment]
> > https://speech.microsoft.com/audiocontentcreation 新的接口在这里
> 
> 这个我也知道，这个用起来感觉还不如edge的接口

https://chrome.google.com/webstore/detail/microsoft-text-to-speech/dplnecggiofdkdcagdkjebneaonfhbbb/related?utm_source=chrome-ntp-icon  安装这个谷歌插件，可以弹出原Demo页面

**Comment by LokerL** [comment]
> > > https://speech.microsoft.com/audiocontentcreation 新的接口在这里
> > 
> > 
> > 这个我也知道，这个用起来感觉还不如edge的接口
> 
> https://chrome.google.com/webstore/detail/microsoft-text-to-speech/dplnecggiofdkdcagdkjebneaonfhbbb/related?utm_source=chrome-ntp-icon 安装这个谷歌插件，可以弹出原Demo页面

可以直接发我一份吗？

**Comment by 0000duck** [comment]
***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年4月8日 22:38
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            Ten Years A ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [LokerL/tts-vue] 已无法使用，微软又更新什么了？做等tts-vue更新！！！！ (Issue #101)
        
      
    
  




https://speech.microsoft.com/audiocontentcreation 新的接口在这里

这个我也知道，这个用起来感觉还不如edge的接口

https://chrome.google.com/webstore/detail/microsoft-text-to-speech/dplnecggiofdkdcagdkjebneaonfhbbb/related?utm_source=chrome-ntp-icon 安装这个谷歌插件，可以弹出原Demo页面

可以直接发我一份吗？

**Comment by 0000duck** [comment]
> > > > https://speech.microsoft.com/audiocontentcreation 新的接口在这里
> > > 
> > > 
> > > 这个我也知道，这个用起来感觉还不如edge的接口
> > 
> > 
> > https://chrome.google.com/webstore/detail/microsoft-text-to-speech/dplnecggiofdkdcagdkjebneaonfhbbb/related?utm_source=chrome-ntp-icon 安装这个谷歌插件，可以弹出原Demo页面
> 
> 可以直接发我一份吗？

已发  806076693@qq.com 。解压后用谷歌浏览器加载已解压的扩展程序

**Comment by 0000duck** [comment]
https://www.microsoft-tts-downloader.com/  插件网址

**Comment by 0000duck** [comment]
> 已无法使用，微软又更新什么了？做等tts-vue更新！！！！
https://www.microsoft-tts-downloader.com/ 
Microsoft™ Text-to-Speech Downloader
Download Microsoft Text-to-Speech website demo app synthesized speech with 1 click.

**Comment by LokerL** [comment]
> > > > > https://speech.microsoft.com/audiocontentcreation 新的接口在这里
> > > > 
> > > > 
> > > > 这个我也知道，这个用起来感觉还不如edge的接口
> > > 
> > > 
> > > https://chrome.google.com/webstore/detail/microsoft-text-to-speech/dplnecggiofdkdcagdkjebneaonfhbbb/related?utm_source=chrome-ntp-icon 安装这个谷歌插件，可以弹出原Demo页面
> > 
> > 
> > 可以直接发我一份吗？
> 
> 已发 [806076693@qq.com](mailto:806076693@qq.com) 。解压后用谷歌浏览器加载已解压的扩展程序

我研究了实现原理，用的是https://speech.microsoft.com/audiocontentcreation 这个网站的接口。但是这个不太好用感觉，我试试吧。

**Comment by tch1121** [comment]
```
https://github.com/tch1121/my-user-script/raw/main/wryyxz.user.js
```

**Comment by gzsxxny** [comment]
> > 微软好像关闭了免费的接口
> 
> 我有别的软件能用微软语音服务，还不会出现网络问题，但是联系作者（tts-vue）想发给她看看，作者并没有回复我，我还给他进行了微信转载试图联系他

@CHEN6311 求大佬分享，急用

**Comment by orangeagain** [comment]
edge的朗读，他有高亮当前单词，这个不知道怎么做的，神奇

**Comment by OhMy-Git** [comment]
能否做个能弹性更换接口网址的介面输入口，这个不行就切换 edge 的接口应急，
或是切换到网友新发现的接口处，这样只要更换掉预设接口就行。
纯新手发言。还是谢谢作者辛苦。

**Comment by LokerL** [comment]
@zxpyld3x @0000duck @orangeagain @tch1121 已更新

**Comment by z191010** [comment]
@LokerL 微软接口现在不能免费用了，大佬后面还更新吗？
