### ISSUE TITLE
[Bug] the title of bug report

### ISSUE THREAD

**Issue by CHEN6311** [LokerL/tts-vue#102]
我找寻找到tts-vue这款软件的时候，也寻找到了很多用微软语音的软件，只是他们怎么好用，所以一直用的都是tts-vue，但是这个软件一直有网络连接不上的问题，我寻找的别的软件都没有，我一直想把那些软件反馈给tts-vue作者，甚至还有微信转账试图联系。但是tts-vue的作者一直没有回复我的留言。所以我想作者主动联系一下我，也因为最后你的软件崩了，我给你提供一下别人做的用微软AI语音的软件，你看看他们的端口，进行一下改进

**Comment by CHEN6311** [comment]
作者看到能否联系一下我呢，或者回复一下我wx的转账留言呢？

**Comment by LokerL** [comment]
我知道edge的接口，也知道怎么使用。
但是我也有我自己的工作，并且最近工作很忙。
维护这个项目很耗费时间，只能抽空去改。

**Comment by CHEN6311** [comment]
加油！

**Comment by dfzf** [comment]
我真的好依赖你作者，辛苦了，等你
