### ISSUE TITLE
手动艾特作者爸爸，大概什么时候能恢复正常使用，真的很需要作者爸爸的帮忙。

### ISSUE THREAD

**Issue by dfzf** [LokerL/tts-vue#104]
急急急

**Comment by qingmeipve** [comment]
这是一个在线的服务，轻点用，别给整崩溃了：https://www.text-to-speech.cn/

**Comment by mochou37** [comment]
> 

确实可以用，厉害啊

**Comment by LokerL** [comment]
源代码已更新。预计2小时后上线安装包。版本号1.9.0。 @qingmeipve @mochou37 @dfzf
