### ISSUE TITLE
作者大大可以参考一下哦，这个网站是可以的

### ISSUE THREAD

**Issue by liulyfly** [LokerL/tts-vue#106]
作者大大可以参考一下哦，这个网站是可以的：https://ttsmaker.com/zh-cn，也是微软的语音包

**Comment by chinsansan** [comment]
https://www.text-to-speech.cn/ 这个网站也可以，能选择语气模式。

**Comment by emeifeng6** [comment]
> 作者大大可以参考一下哦，这个网站是可以的：[https://ttsmaker.com/zh-cn，也是微软的语音包](https://ttsmaker.com/zh-cn%EF%BC%8C%E4%B9%9F%E6%98%AF%E5%BE%AE%E8%BD%AF%E7%9A%84%E8%AF%AD%E9%9F%B3%E5%8C%85)

打开404~,原来是链接少一个空格了哇

[https://ttsmaker.com/zh-cn](https://ttsmaker.com/zh-cn)

**Comment by LokerL** [comment]
源代码已更新。预计2小时后上线安装包。版本号1.9.0。 @liulyfly @chinsansan @chinsansan
