### ISSUE TITLE
[Bug]  SSML比较长不能自动播放。不能保存

### ISSUE THREAD

**Issue by 0000duck** [LokerL/tts-vue#110]
下载保存到哪里了？找不到。   SSML比较长不能自动播放。

**Comment by 0000duck** [comment]
<speak  xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts" xmlns:emo="http://www.w3.org/2009/10/emotionml" version="1.0" xml:lang="en-US">
<voice  name="zh-CN-YunyangNeural">
    <mstts:express-as style="poetry-reading">
        <prosody  rate="0%" pitch="0%">几何课上，老师提问一学生：</prosody>
    </mstts:express-as>
</voice>
<voice  name="zh-CN-XiaoxiaoNeural">
    <mstts:express-as style="affectionate">
        <prosody  rate="0%" pitch="0%">“由线和面组成的是什么？”</prosody>
    </mstts:express-as>
</voice>
<voice  name="zh-CN-YunfengNeural">
    <mstts:express-as style="serious">
        <prosody  rate="0%" pitch="0%">“馅和面？饺子呗！”</prosody>
    </mstts:express-as>
</voice>
<voice  name="zh-CN-XiaoxiaoNeural">
    <mstts:express-as style="affectionate">
        <prosody  rate="0%" pitch="0%">大家都在笑，为什么你不笑？</prosody>
    </mstts:express-as>
</voice>
<voice  name="zh-CN-YunfengNeural">
    <mstts:express-as style="fearful">
        <prosody  rate="0%" pitch="0%">我不敢笑。</prosody>
    </mstts:express-as>
</voice>
<voice  name="zh-CN-XiaoxiaoNeural">
    <mstts:express-as style="affectionate">
        <prosody  rate="0%" pitch="0%">为什么呢？</prosody>
    </mstts:express-as>
</voice>
<voice  name="zh-CN-YunfengNeural">
    <mstts:express-as style="depressed">
        <prosody  rate="0%" pitch="0%">您常说笑一笑，10年少，我今天刚满10岁，再一笑不就没了。</prosody>
    </mstts:express-as>
</voice>
<voice  name="zh-CN-YunxiNeural">
    <mstts:express-as style="narration-relaxed">
        <prosody  rate="0%" pitch="0%">老师问小明：</prosody>
    </mstts:express-as>
</voice>
<voice  name="zh-CN-XiaoxiaoNeural">
    <mstts:express-as style="affectionate">
        <prosody  rate="0%" pitch="0%">“如果你考试不及格，你的父母会怎么对待你”？</prosody>
    </mstts:express-as>
</voice>
<voice  name="zh-CN-YunhaoNeural">
    <mstts:express-as style="general">
        <prosody  rate="0%" pitch="0%">“80”分以下是女子单打。“70”分以下是男子单打。如果是“60”分以下是男女混合双打!</prosody>
    </mstts:express-as>
</voice>
<voice  name="zh-CN-YunxiNeural">
    <mstts:express-as style="narration-relaxed">
        <prosody  rate="0%" pitch="0%">下课了，老师说：</prosody>
    </mstts:express-as>
</voice>
<voice  name="zh-CN-XiaoxiaoNeural">
    <mstts:express-as style="affectionate">
        <prosody  rate="0%" pitch="0%">最后我还要讲一点……</prosody>
    </mstts:express-as>
</voice>
<voice  name="zh-CN-YunxiNeural">
    <mstts:express-as style="narration-relaxed">
        <prosody  rate="0%" pitch="0%">一学生：</prosody>
    </mstts:express-as>
</voice>
<voice  name="zh-CN-YunjianNeural">
    <mstts:express-as style="general">
        <prosody  rate="0%" pitch="0%">强扭的瓜不甜！</prosody>
    </mstts:express-as>
</voice>
<voice  name="zh-CN-XiaoxiaoNeural">
    <mstts:express-as style="affectionate">
        <prosody  rate="0%" pitch="0%">请用“恳求”和“要求”造句。 　</prosody>
    </mstts:express-as>
</voice>
<voice  name="zh-CN-YunjianNeural">
    <mstts:express-as style="general">
        <prosody  rate="0%" pitch="0%">昨天妈妈炖了一锅猪脚，还没熟的时候爸爸吃了一块，说：“恳求不动”。妈妈说：“要求你啃”</prosody>
    </mstts:express-as>
</voice>
<voice  name="zh-CN-YunxiNeural">
    <mstts:express-as style="narration-relaxed">
        <prosody  rate="0%" pitch="0%">班主任训斥调皮的学生：</prosody>
    </mstts:express-as>
</voice>
<voice  name="zh-CN-XiaoxiaoNeural">
    <mstts:express-as style="angry">
        <prosody  rate="0%" pitch="0%">你此人，仰高个屁股就知你屙尿或屙屎。。。</prosody>
    </mstts:express-as>
</voice>
<voice  name="zh-CN-YunxiNeural">
    <mstts:express-as style="general">
        <prosody  rate="0%" pitch="0%">学生很认真地说：</prosody>
    </mstts:express-as>
</voice>
<voice  name="zh-CN-YunxiaNeural">
    <mstts:express-as style="general">
        <prosody  rate="0%" pitch="0%">错！我没屙尿更没屙屎！只是屙屁罢了！</prosody>
    </mstts:express-as>
</voice>
<voice  name="zh-CN-XiaoxiaoNeural">
    <mstts:express-as style="affectionate">
        <prosody  rate="0%" pitch="0%">你讲讲举世无双一词的意思。</prosody>
    </mstts:express-as>
</voice>
<voice  name="zh-CN-YunxiaNeural">
    <mstts:express-as style="general">
        <prosody  rate="0%" pitch="0%">‘举世’，就是出世，‘无双’，就是无双亲。‘举世无双，就是一出世就没有父母呗！</prosody>
    </mstts:express-as>
</voice>
<voice  name="zh-CN-YunjianNeural">
    <mstts:express-as style="general">
        <prosody  rate="0%" pitch="0%">老师，我错了，我是混蛋。</prosody>
    </mstts:express-as>
</voice>
<voice  name="zh-CN-XiaoxiaoNeural">
    <mstts:express-as style="affectionate">
        <prosody  rate="0%" pitch="0%">嗯，你是混蛋，但还不算坏蛋。</prosody>
    </mstts:express-as>
</voice>
</speak>

**Comment by LokerL** [comment]
是不能转换成功还是转换成功了没有自动播放？

**Comment by 0000duck** [comment]
长的ssml显示转换成功，但是不能播放，也不能保存。分成小段ssml可以。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月19日(周三) 中午11:14
收件人: ***@***.***&gt;;
抄送: "Ten Years A ***@***.******@***.***&gt;;
主题: Re: [LokerL/tts-vue] [Bug]  SSML比较长不能自动播放。不能保存 (Issue #110)




 
是不能转换成功还是转换成功了没有自动播放？

**Comment by LokerL** [comment]
SSML不支持长文本切片。
