### ISSUE TITLE
[Help] 很长的文本语音合成，即使有切片功能，还是只能转换一部分。

### ISSUE THREAD

**Issue by 0000duck** [LokerL/tts-vue#122]
语音合成文本输入最大长度有限制吗？我把8887个字（博客文章）输入进去，让她语音合成，会报错。有一次合成成功了，但是只有三分之一的文字进行了合成。

**Comment by LokerL** [comment]
调用接口频率太高被微软限制了。
试试分时段转换，上午转4000字，下午转4000字
