### ISSUE TITLE
[Bug] 429 - too many requests

### ISSUE THREAD

**Issue by taozhiyu** [LokerL/tts-vue#127]
#### Describe the bug

Error: Error invoking remote method 'speech': AxiosError: Request failed with status code 429

**Comment by LokerL** [comment]
暂时没法解决。后面版本加入edge朗读多个选择吧。

**Comment by orangeagain** [comment]
> 暂时没法解决。后面版本加入edge朗读多个选择吧。

这是因为微软的速率限制，如果增加一个速率选项，排队发送请求就可以解决这个问题

**Comment by XBIGA** [comment]
怎么解决啊
