### ISSUE TITLE
初次打开时只有图标

### ISSUE THREAD

**Issue by lizipeng0013** [LokerL/tts-vue#129]
#### Describe the bug
初次打开软件时，只有软件图标而不显示软件界面，将软件结束运行后第二次打开就正常了
软件版本：1.9.9

**Comment by gedo1018** [comment]
我也是，但是第二次打开还是不能运行，求助

**Comment by willing007** [comment]
软件还是打不开，只有图标，求助

**Comment by lizipeng0013** [comment]
现在只能多试几次，有时能打开，有时只有图标

**Comment by lizipeng0013** [comment]
最新的1.9.10依旧是初次运行只显示图标
何为初次运行：
在C:\Users\用户名\AppData\Roaming\下没有tts-vue这个文件夹，软件在初次运行时会创建，把此文件夹删除后，再次打开软件又会再次创建，这种情况下第一次打开软件不显示界面

**Comment by willing007** [comment]
早上用的是1.9.3当时还好，提醒要更新，我关闭软件后更新，就再没有打开过

**Comment by willing007** [comment]
更新到1.9.9

**Comment by lihhhh** [comment]
试试 https://github.com/lihhhh/tts-vue

**Comment by willing007** [comment]
谢谢，可以用

**Comment by LokerL** [comment]
已更新1.9.10
