### ISSUE TITLE
一篇千字文转为语音耗时太长了

### ISSUE THREAD

**Issue by freemancash** [LokerL/tts-vue#13]
一篇千字文转为语音耗时太长了，能否想另一个朗读软件balabolka那样不要等文本全部转为语音在朗读呢？

**Comment by LokerL** [comment]
这里是官方的说明，不清楚是不是和demo的接口一样。
![image](https://user-images.githubusercontent.com/44148627/187927622-eaa70dda-6949-42d2-98ac-d098f17007ec.png)

**Comment by LokerL** [comment]
> 能否想另一个朗读软件balabolka那样不要等文本全部转为语音在朗读呢？

这个公共接口功能没那么多，要是使用注册后提供的那些API好像可以实现这个功能。但是对于这个项目来说，实现起来还是有些困难。
