### ISSUE TITLE
打不开

### ISSUE THREAD

**Issue by catis114514** [LokerL/tts-vue#132]

**Comment by LokerL** [comment]
什么版本？

**Comment by catis114514** [comment]
最新版本

**Comment by catis114514** [comment]
没事了，sbwin10又又又发癫了

**Comment by LokerL** [comment]
软件打不开，可以试试
1. 右键桌面图标→打开文件所在位置
2. 在软件安装目录，shift+右键在此处打开powershell窗口；或者地址栏输入cmd回车
3. 在出现的powershell窗口或者cmd窗口输入`.\tts-vue.exe`或者`tts-vue.exe`，回车
4. 截图输出的内容 以及 软件首页发送到这里

**Comment by catis114514** [comment]
抱歉
