### ISSUE TITLE
文本太长导致的问题

### ISSUE THREAD

**Issue by 866837** [LokerL/tts-vue#133]
在文本或批量中，如果文本过长，会导致只转换其中一部分为语音，其余部分则不会被转换。
文稿总长4643字，实际只会转换约3500字左右。
这是接口的限制吗

**Comment by lihhhh** [comment]
试试这个 https://github.com/lihhhh/tts-vue

**Comment by 866837** [comment]
非常感谢 你帮了我大忙

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
