### ISSUE TITLE
转换失败 Error: Error invoking remote method 'speech': AxiosError: Request failed with status code 400

### ISSUE THREAD

**Issue by retertretert** [LokerL/tts-vue#134]
我的文本合共约700字符（使用SSML加了停顿），为什么会出现“转换失败 Error: Error invoking remote method 'speech': AxiosError: Request failed with status code 400”？

**Comment by lihhhh** [comment]
大概率是你的ssml有问题,你可以贴出来看看

**Comment by retertretert** [comment]
> 大概率是你的ssml有问题,你可以贴出来看看

<speak xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts" xmlns:emo="http://www.w3.org/2009/10/emotionml" version="1.0" xml:lang="en-US">
        <voice name="zh-CN-XiaoxiaoNeural">
            <mstts:express-as  style="Default" >
                <prosody rate="-20%" pitch="0%">
1。灭亡<break time="2000ms"/>灭亡<break time="40000ms"/>
2。肥沃<break time="2000ms"/>肥沃<break time="40000ms"/>
3。羡慕<break time="2000ms"/>羡慕<break time="40000ms"/>
4。凝视<break time="2000ms"/>凝视<break time="40000ms"/>
5。连绵<break time="2000ms"/>连绵<break time="40000ms"/>
6。干燥<break time="2000ms"/>干燥<break time="40000ms"/>
7。砍伐<break time="2000ms"/>砍伐<break time="40000ms"/>
8。怀念<break time="2000ms"/>怀念<break time="20000ms"/>
9。紧密<break time="2000ms"/>紧密<break time="20000ms"/>
10。降临<break time="2000ms"/>降临<break time="40000ms"/>
11。雀跃<break time="2000ms"/>雀跃<break time="40000ms"/>
12。熊猫<break time="2000ms"/>熊猫<break time="40000ms"/>
13。皱纹<break time="2000ms"/>皱<break time="40000ms"/>
14。诊断<break time="2000ms"/>诊断<break time="40000ms"/>
15。衬托<break time="2000ms"/>衬托<break time="40000ms"/>
16。诚恳<break time="2000ms"/>诚恳<break time="40000ms"/>
17。摔跤<break time="2000ms"/>摔跤<break time="40000ms"/>
18。走廊<break time="2000ms"/>走廊<break time="40000ms"/>
19。刻苦<break time="2000ms"/>刻苦<break time="40000ms"/>
20。幽默<break time="2000ms"/>幽默<break time="40000ms"/>
21。毛茸茸<break time="2000ms"/>毛茸茸<break time="30000ms"/><break time="30000ms"/><break time="30000ms"/>
22。暖烘烘<break time="2000ms"/>暖烘烘<break time="30000ms"/><break time="30000ms"/><break time="30000ms"/>
23。孤零零<break time="2000ms"/>孤零零<break time="30000ms"/><break time="30000ms"/><break time="30000ms"/>
24。香喷喷<break time="2000ms"/>香喷喷<break time="30000ms"/><break time="30000ms"/><break time="30000ms"/>
25。奔流不息<break time="2000ms"/>奔流不息<break time="40000ms"/><break time="40000ms"/><break time="40000ms"/>
26。不知所措<break time="2000ms"/>不知所措<break time="40000ms"/><break time="40000ms"/><break time="40000ms"/>
27。明察秋毫<break time="2000ms"/>明察秋毫<break time="40000ms"/><break time="40000ms"/><break time="40000ms"/>
28。奋不顾身<break time="2000ms"/>奋不顾身<break time="40000ms"/><break time="40000ms"/><break time="40000ms"/>
29。千变万化<break time="2000ms"/>千变万化<break time="40000ms"/><break time="40000ms"/><break time="40000ms"/>
30。情不自禁<break time="2000ms"/>情不自禁<break time="40000ms"/><break time="40000ms"/><break time="40000ms"/>
31。全神贯注<break time="2000ms"/>全神贯注<break time="40000ms"/><break time="40000ms"/><break time="40000ms"/>
32。势不可挡<break time="2000ms"/>势不可挡<break time="40000ms"/><break time="40000ms"/><break time="40000ms"/>
33。水平如镜<break time="2000ms"/>水平如镜<break time="40000ms"/><break time="40000ms"/><break time="40000ms"/>
34。足不出户<break time="2000ms"/>足不出户<break time="40000ms"/><break time="40000ms"/><break time="40000ms"/>
35。四面楚歌<break time="2000ms"/>四面楚歌<break time="40000ms"/><break time="40000ms"/><break time="40000ms"/>
36。一扫而光<break time="2000ms"/>一扫而光<break time="40000ms"/><break time="40000ms"/><break time="40000ms"/>
一共36个，现在将所有字词重复朗读一遍。<break time="2000ms"/>
1。灭亡。2。肥沃。3。羡慕。4。凝视。5。连绵。6。干燥。7。砍伐。8。怀念。9。紧密。10。降临。11。雀跃。12。熊猫。13。皱纹。14。诊断。15。衬托。16。诚恳。17。摔跤。18。走廊。19。刻苦。20。幽默。21。毛茸茸。22。暖烘烘。23。孤零零。24。香喷喷。25。奔流不息。26。不知所措。27。明察秋毫。28。奋不顾身。29。千变万化。30。情不自禁。31。全神贯注。32。势不可挡。33。水平如镜。34。足不出户。35。四面楚歌。36。一扫而光。
                </prosody>
            </mstts:express-as>
        </voice>
    </speak>

**Comment by lihhhh** [comment]
两种可能
1、应该是文本超长了 你设置300个字保险一点
2、你的break设置的时间有问题 40000ms 是40秒的停顿,你确定?
