### ISSUE TITLE
提示：转换失败 Error: Error invoking remote method 'azureApi': [object Object]  第三个接口总是提示这个怎么办？求助

### ISSUE THREAD

**Issue by X-Chen-fan** [LokerL/tts-vue#135]
#### Describe the problem you confuse
提示：转换失败 Error: Error invoking remote method 'azureApi': [object Object]  第三个接口总是提示这个怎么办？求助

![image](https://github.com/LokerL/tts-vue/assets/69028375/4d98f22e-3c77-4712-ba41-d931836b09bf)

**Comment by LokerL** [comment]
不会用那就不用第三个接口呗
[Azure Speech API使用，key和region获取](https://tts-doc.loker.vip/guide/qa.html#azure-speech-api%E4%BD%BF%E7%94%A8-key%E5%92%8Cregion%E8%8E%B7%E5%8F%96)

**Comment by Raxcl** [comment]
![image](https://github.com/LokerL/tts-vue/assets/70327089/4da3b74d-b0e8-4e86-8c3f-e19958401b8b)
同样的问题，我是在保存key和region的时候报的404，求问大佬是不是我的配置有问题
![image](https://github.com/LokerL/tts-vue/assets/70327089/a71da58c-8597-4952-813c-27bef83da037)
试着开关了vpn，还是没有解决

**Comment by Raxcl** [comment]
> #### Describe the problem you confuse
> 提示：转换失败 Error: Error invoking remote method 'azureApi': [object Object] 第三个接口总是提示这个怎么办？求助
> 
> ![image](https://user-images.githubusercontent.com/69028375/257522624-4d98f22e-3c77-4712-ba41-d931836b09bf.png)

region地区位置有点坑，我的是 eastasia，不能安装官方的带空格的英文去填写（可能是我没找到教程入口吧），就可以了
