### ISSUE TITLE
[Bug] the title of bug report

### ISSUE THREAD

**Issue by ChaoYou-Li** [LokerL/tts-vue#137]
#### Describe the bug
软件安装后点击打开，没反应呢

**Comment by LokerL** [comment]
可能的原因：
- 因为软件打开时会访问微软的一个api去获取最新的语言语音说话风格角色，然后因为电脑的网络连接微软服务器很慢导致软件UI无法立刻显示出来
可能的解决方案：
- 等待

其他：
软件打不开，可以试试
1. 右键桌面图标→打开文件所在位置
2. 在软件安装目录，shift+右键在此处打开powershell窗口；或者地址栏输入cmd回车
3. 在出现的powershell窗口或者cmd窗口输入“.\tts-vue.exe”或者“tts-vue.exe”不带引号，回车
4. 截图输出的内容贴到这里
