### ISSUE TITLE
怎么可以进行多人配音，比如配置对话的方式

### ISSUE THREAD

**Issue by Kuron88** [LokerL/tts-vue#143]
#### Describe the problem you confuse

![QQ截图20230904134616](https://github.com/LokerL/tts-vue/assets/29248355/e96b47dd-7acc-468c-b0a9-5c24a1348ec6)

**Comment by LokerL** [comment]
可以试试SSML标签，但是SSML标签不支持长文本切片，且只能自己编辑SSML，不支持自动生成。
