### ISSUE TITLE
转换失败 Error: Speech invocation failed after 10 retries

### ISSUE THREAD

**Issue by OakHoo** [LokerL/tts-vue#144]
转换失败 Error: Speech invocation failed after 10 retries

**Comment by LokerL** [comment]
大概率是10次429

**Comment by 17392124899** [comment]
我也出现这个问题
转换失败 Error: Speech invocation failed after 10 retries
怎么解决呀

**Comment by hangqian93** [comment]
这个问题怎么解决error: Speech invocation failed after 10 retries

**Comment by ruohai0925** [comment]
也遇到了这个问题

**Comment by NekoFox6** [comment]
应该是API被换掉了，建议使用自己的speech key
