### ISSUE TITLE
能否通过命令执行本软件？？

### ISSUE THREAD

**Issue by achirand** [LokerL/tts-vue#148]
通过命令执行本软件？？

例如windows系统里，bat文件，或者cmd窗口里
**tts-vue.exe   文本txt文件  配置参数   音频保存文件**

或者python执行
**python tts-vue.exe   文本txt文件  配置参数   音频保存文件**

请看能否通过命令方式执行以上软件？

**Comment by LokerL** [comment]
暂时不行，近期也没有实现这个功能的打算
