### ISSUE TITLE
[Help] 请问有人知道多音字怎么设置吗？

### ISSUE THREAD

**Issue by oleola** [LokerL/tts-vue#20]
微软官方有文档吗？还是软件可以直接设置？

**Comment by LokerL** [comment]
文本内容输入这个试试，简单的读音例子：

> 你好啊
> 读<phoneme alphabet="sapi" ph="chong 2 liang 4">重量</phoneme>是不对的
> 要读成“重量”
![image](https://user-images.githubusercontent.com/44148627/187923533-5f0a2375-c685-475e-9e51-d0ef3c3ce19e.png)



详情可以看：[使用音素改善发音](https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/speech-synthesis-markup?tabs=csharp#use-phonemes-to-improve-pronunciation)

**Comment by oleola** [comment]
谢谢大佬回复，这样就能解决我一个大问题了，再次感谢！
