### ISSUE TITLE
[Help] 字数4000-6000左右的TXT批量好慢

### ISSUE THREAD

**Issue by holduan** [LokerL/tts-vue#22]
#### Describe the problem you confuse
如题，请问怎么解决，可以优化一下吗，网页版的工具[toolb.cn/textspeech](https://toolb.cn/textspeech)还挺快的。

**Comment by LokerL** [comment]
官方的说明不能超过1000字符，但是我测试的超过400字符可能就有问题了。400以内没问题。

**Comment by holduan** [comment]
> 官方的说明不能超过1000字符，但是我测试的超过400字符可能就有问题了。400以内没问题。

不能增加个自动断开文字去识别，然后再把音频拼在一起吗

**Comment by LokerL** [comment]
> > 官方的说明不能超过1000字符，但是我测试的超过400字符可能就有问题了。400以内没问题。
> 
> 不能增加个自动断开文字去识别，然后再把音频拼在一起吗

可以，但是最近工作比较多，近期没时间去维护这个项目了。大概要等到10月初吧。

**Comment by holduan** [comment]
> 

嗯嗯，多谢 ❤
