### ISSUE TITLE
[Help] 不知道音频可不可以转成m4a，体积小一点

### ISSUE THREAD

**Issue by holduan** [LokerL/tts-vue#30]

**Comment by LokerL** [comment]
可以，官方的api写得比较模糊，我对这一块也不太了解。弄起来可能会比较麻烦。
以下是官方支持的输出流，但是不清楚那个是m4a支持的。。
> 流式处理 | 非流式处理
> -- | --
> audio-16khz-16bit-32kbps-mono-opus | riff-8khz-8bit-mono-alaw
> audio-16khz-32kbitrate-mono-mp3 | riff-8khz-8bit-mono-mulaw
> audio-16khz-64kbitrate-mono-mp3 | riff-8khz-16bit-mono-pcm
> audio-16khz-128kbitrate-mono-mp3 | riff-22050hz-16bit-mono-pcm
> audio-24khz-16bit-24kbps-mono-opus | riff-24khz-16bit-mono-pcm
> audio-24khz-16bit-48kbps-mono-opus | riff-44100hz-16bit-mono-pcm
> audio-24khz-48kbitrate-mono-mp3 | riff-48khz-16bit-mono-pcm
> audio-24khz-96kbitrate-mono-mp3 |  
> audio-24khz-160kbitrate-mono-mp3 |  
> audio-48khz-96kbitrate-mono-mp3 |  
> audio-48khz-192kbitrate-mono-mp3 |  
> ogg-16khz-16bit-mono-opus |  
> ogg-24khz-16bit-mono-opus |  
> ogg-48khz-16bit-mono-opus |  
> raw-8khz-8bit-mono-alaw |  
> raw-8khz-8bit-mono-mulaw |  
> raw-8khz-16bit-mono-pcm |  
> raw-16khz-16bit-mono-pcm |  
> raw-16khz-16bit-mono-truesilk |  
> raw-22050hz-16bit-mono-pcm |  
> raw-24khz-16bit-mono-pcm |  
> raw-24khz-16bit-mono-truesilk |  
> raw-44100hz-16bit-mono-pcm |  
> raw-48khz-16bit-mono-pcm |  
> webm-16khz-16bit-mono-opus |  
> webm-24khz-16bit-24kbps-mono-opus |  
> webm-24khz-16bit-mono-opus
