### ISSUE TITLE
一个小bug，当文本中含有“&”时会出错

### ISSUE THREAD

**Issue by 6Tom** [LokerL/tts-vue#37]
#### Describe the bug
```
手动替换“&”为“&amp;”
```
即可解决问题，所以是一个小bug，主要是发现了，就反馈上来了

软件真的很棒，非常感谢大佬的辛苦付出，祝生活愉快

**Comment by LokerL** [comment]
所有文本内容直接发送给微软的WS接口，软件不对文本内容做修改。这个问题以前就发现了。。。
据测试，接口接收的文本内容还不能包含任何无法解析的标签语言。
