### ISSUE TITLE
关于批量转换数量的问题

### ISSUE THREAD

**Issue by wbcamn** [LokerL/tts-vue#39]
感谢作者的奉献，一个非常好用的项目，帮助我解决了语音转换的一个大问题。
我在使用的过程中发现了一个问题，我导入了400多个TXT进行转换，刚开始转换速度很快，但是只完成了250个左右，剩下的不能继续转换，而后查看日志发现，一直卡在创建链接上，具体日志如下：
[2022-10-21 21:22:56.573] [info]  
    <speak xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts" xmlns:emo="http://www.w3.org/2009/10/emotionml" version="1.0" xml:lang="en-US">
        <voice name="zh-CN-XiaoxiaoNeural">
            <mstts:express-as   >
                <prosody rate="0%" pitch="0%">
                你好啊
今天天气怎么样?
                </prosody>
            </mstts:express-as>
        </voice>
    </speak>
    
[2022-10-21 21:22:56.576] [info]  创建webscoket连接...

重启程序后依然不能使用，网络连接测试正常，但是切换到手机热点后可以继续使用。怀疑是接口调用超过了微软的限制，导致IP或KEY被短时间封禁，请问这个限制是什么？我看了下微软的文档看的不是很明白，能否在批量转换的时候加入延时或限制，防止此类情况的发生？
再次感谢作者的付出，祝愿作者身体健康、工作顺利。

**Comment by wbcamn** [comment]
也有可能是请求太多，导致部分请求丢失了，可以考虑优化一下。

**Comment by LokerL** [comment]
感谢支持，批量转换中的各种BUG在开发计划中，但是因为各种原因没法像项目初期那样高频率的开发和更新了，我会尽量去维护这个项目。
