### ISSUE TITLE
[Help] 全是英文，还是停在第3次上报... 

### ISSUE THREAD

**Issue by li1008611** [LokerL/tts-vue#42]
求助大佬，全是英文的词，大概5、6十行, 600个词不到，没有&和标签语言，还是停在第3次上报... /(ㄒoㄒ)/~~
一直卡在转圈和请稍后

**Comment by li1008611** [comment]
但是拆开来又行了...
是不是有长度限制啊？

**Comment by li1008611** [comment]
是路径的原因，就算不用那个批量，也是要换个路径，😂

**Comment by LokerL** [comment]
默认保存位置是桌面，有的人打开软件后下载保存到桌面是没有权限的。
