### ISSUE TITLE
[Help] the title of help wanted report

### ISSUE THREAD

**Issue by sleechengn** [LokerL/tts-vue#44]
#### Describe the problem you confuse
作者您好，因为是electorn作为项目层层框架，是跨平台的框架，能不能提供一个macos的发行版，这样在macos上就能很好的使用了

**Comment by LokerL** [comment]
不会发行除windows以外的版本，因为无法测试软件UI以及稳定性。
有需求推荐clone代码，自行编译
或者fork代码，修改/.github/workflows/main.yml的自动化打包相关代码让github给你打包。
