### ISSUE TITLE
多音字翻译问题，不知道咋弄

### ISSUE THREAD

**Issue by Keeper0005** [LokerL/tts-vue#46]
海祇岛（hai qi dao）读成（hai zhi dao）

**Comment by Keeper0005** [comment]
希望作者加入一个识别多音字转换的功能，让使用者可以更便捷的更换多音字，祝作者身体健康，万事顺利！

**Comment by LokerL** [comment]
[如何调整多音字的读音或添加中断或暂停等](https://loker-page.lgwawork.com/guide/qa.html#%E5%A6%82%E4%BD%95%E8%B0%83%E6%95%B4%E5%A4%9A%E9%9F%B3%E5%AD%97%E7%9A%84%E8%AF%BB%E9%9F%B3%E6%88%96%E6%B7%BB%E5%8A%A0%E4%B8%AD%E6%96%AD%E6%88%96%E6%9A%82%E5%81%9C%E7%AD%89)

试试输入：
```
<phoneme alphabet="sapi" ph="chai 3 qi 2 dao 3">海祇岛</phoneme>
<phoneme alphabet="sapi" ph="chai 3 zhi 3 dao 3">海祇岛</phoneme>

```
![image](https://user-images.githubusercontent.com/44148627/203893817-6b4750f2-66a6-4cb1-996d-b15dc4e14821.png)
