### ISSUE TITLE
[Help] 有没有Mac版本

### ISSUE THREAD

**Issue by mailes** [LokerL/tts-vue#48]
#### Describe the problem you confuse
怎么打包一个mac版本的。请指教。M1芯片的。

**Comment by mailes** [comment]
会了。

**Comment by mailes** [comment]
> 如何生成MAC版的呢

npm run build

**Comment by H-Joe** [comment]
> > 如何生成MAC版的呢
> 
> npm run build

thk

**Comment by chinsansan** [comment]
请教，我按照[教程](https://loker-page.lgwawork.com/guide/install.html#%E9%80%9A%E8%BF%87%E6%BA%90%E7%A0%81%E7%BC%96%E8%AF%91)  `npm i`  第一步就显示错误 npm err! code 1 command timedout

**Comment by Cubik65536** [comment]
我创建了一个跨平台分支，可以直接从 Release 或 GitHub Action 下载打包好的程序，如果需要的话可以使用： https://github.com/CubikTech/tts-vue-multiplatform

/cc @chinsansan

**Comment by chinsansan** [comment]
> 我创建了一个跨平台分支，可以直接从 Release 或 GitHub Action 下载打包好的程序，如果需要的话可以使用： https://github.com/CubikTech/tts-vue-multiplatform
> 
> 编辑：如有问题可以在分支仓库的 issue 里提交反馈

哇！赞。感谢创建和分享
