### ISSUE TITLE
[Bug] 希望能完善批量转换的稳定性

### ISSUE THREAD

**Issue by holduan** [LokerL/tts-vue#49]
现在的批量经常失败，成功率太低，txt编码utf-8，批量1个或者5个txt都失败，谢谢。

**Comment by LokerL** [comment]
我测试过多次批量转换4-6篇高考满分作文，用时都在40秒到3分钟不等就转换成功，多次测试没有任何报错。
批量转换是否成功先要看有没有微软接口无法识别的字符
然后还和你的网络有关系
具体问题和解答可以看文档
