### ISSUE TITLE
 批量转换会卡住

### ISSUE THREAD

**Issue by cyz452** [LokerL/tts-vue#55]
但文本6000多字，文本转换没有问题，批量转换就会卡死，日志信息每次卡住都不同，不是网络问题
单一文本内容只是：123123123123也依然会卡住
![image](https://user-images.githubusercontent.com/64049343/207491108-f05eee80-b92e-4776-a288-24e78f7ecf6e.png)

附件是日志信息
[2022-12-14.log](https://github.com/LokerL/tts-vue/files/10223753/2022-12-14.log)

**Comment by LokerL** [comment]
看日志没有任何问题
