### ISSUE TITLE
点击开始转换后 按钮样式变成3个音符图 然后就没有然后了

### ISSUE THREAD

**Issue by 13529387310** [LokerL/tts-vue#59]
<img width="668" alt="微信截图_20221220210056" src="https://user-images.githubusercontent.com/121104705/208673745-8b7d3b74-efba-4602-a571-7d4fd0101fb9.png">

**Comment by 13529387310** [comment]
<img width="668" alt="微信截图_20221220211313" src="https://user-images.githubusercontent.com/121104705/208675530-f9282144-a3fa-4501-8fb7-1d29db333d90.png">

**Comment by 13529387310** [comment]
您好这是什么问题啊

**Comment by LokerL** [comment]
网络问题
