### ISSUE TITLE
[请求] 希望增加下载文件名字的自定义方案

### ISSUE THREAD

**Issue by tanglangxia** [LokerL/tts-vue#62]
希望增加音频下载的名字自定义方案，目前是按照时间戳为名字，可以增加几种其他命名方案吗？

比如“语音配置文件名称”+“文本内容”（前10个字左右）名称，或者“”序号“+”“语音配置文件名称”+时间

增加几个方案便于管理转换的音频，目前都要下载后再逐一的修正下名称，如果有几个名称预设就方便了，谢谢了。

**Comment by LokerL** [comment]
推荐使用批量转换，复制文本内容到txt文件里，最终生成的文件名就是原txt的文件名。
