### ISSUE TITLE
2023年2月5日，21点30左右开始无法文字转化成语音，一直在音符跳动状态。

### ISSUE THREAD

**Issue by LKY1982** [LokerL/tts-vue#66]
2023年2月5日，21点30左右开始无法文字转化成语音，一直在音符跳动状态。

**Comment by LKY1982** [comment]
软件非常好用，万份感谢。但不知道这个问题什么时候能解决，再次感谢。

**Comment by LokerL** [comment]
2023年2月6日上午9点40分测试没问题，检查下自己的网络状况。

**Comment by LKY1982** [comment]
是的，我这会测试也没问题了。谢谢您，万谢。
