### ISSUE TITLE
3月6日晚上到3月7日早上9点30一直是报错状态，无法合成语音，具体报错如图。

### ISSUE THREAD

**Issue by LKY1982** [LokerL/tts-vue#67]
![image](https://user-images.githubusercontent.com/124514901/217127017-4a737c84-f3ce-4af2-a96d-4cbaea013186.png)

**Comment by LKY1982** [comment]
检查了自己的网络，网络是正常的。开启代理可以访问外网，尝试转化语音也失败，关闭代理，确认网络畅通，尝试转化语音继续失败，报错内容如上图。

**Comment by jusic890** [comment]
同样问题，无法合成语音，是什么原因呢

**Comment by LokerL** [comment]
猜测有可能是微软那边的服务端导致网络异常

**Comment by LokerL** [comment]
2023.02.08 16:48测试功能没问题了。
猜测是微软那边的服务器波动。

**Comment by LKY1982** [comment]
好的，万谢。
