### ISSUE TITLE
转换工作无法正常进行

### ISSUE THREAD

**Issue by Vin-Xing** [LokerL/tts-vue#69]
#### Describe the bug
转换开始后，一直卡在转换进行中，多长时间都无法转换完成，同样六千多字的文本，之前都是一分多钟甚至不到一分钟就可以转换完成，现在无论多久都无法转换。

**Comment by DavidXuKui** [comment]
mac版本有吗

**Comment by LokerL** [comment]
似乎是微软那边的服务器问题
