### ISSUE TITLE
[Bug] the title of bug report

### ISSUE THREAD

**Issue by zspzip** [LokerL/tts-vue#71]
#### Describe the bug
创建webscoket连接...
index.dc1a0429.js:18 F1AEC43AF0694F9F8023C9CCE3703421
2node:events:504 Uncaught Error: Invalid handshake: invalid first line format
    at Connection.checkHandshake (D:\视频资源\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:375:22)
    at Connection.readHandshake (D:\视频资源\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:331:54)
    at Connection.doRead (D:\视频资源\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:246:13)
    at TLSSocket.<anonymous> (D:\视频资源\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:66:8)
    at TLSSocket.emit (node:events:526:28)
    at emitReadable_ (node:internal/streams/readable:578:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/ajv.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/core.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/boolSchema.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/errors.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/code.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/scope.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/util.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/dataType.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/rules.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/applicability.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/defaults.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/keyword.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/code.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/subschema.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/resolve.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/validation_error.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/ref_error.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/uri.all.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/id.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/ref.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/limitNumber.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/multipleOf.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/limitLength.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/ucs2length.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/pattern.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/limitProperties.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/required.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/limitItems.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/uniqueItems.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/const.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/enum.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/additionalItems.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/prefixItems.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/items.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/items2020.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/contains.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/dependencies.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/propertyNames.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/additionalProperties.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/properties.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/patternProperties.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/not.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/oneOf.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/allOf.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/if.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/thenElse.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/format.js.map 的内容：Unexpected end of JSON input
2DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/formats.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/limit.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/ajv.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/core.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/boolSchema.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/errors.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/code.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/scope.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/util.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/dataType.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/rules.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/applicability.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/defaults.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/keyword.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/code.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/subschema.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/resolve.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/validation_error.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/ref_error.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/id.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/ref.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/limitNumber.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/multipleOf.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/limitLength.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/ucs2length.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/pattern.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/limitProperties.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/required.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/limitItems.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/uniqueItems.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/const.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/enum.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/additionalItems.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/prefixItems.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/items.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/items2020.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/contains.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/dependencies.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/propertyNames.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/additionalProperties.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/properties.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/patternProperties.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/not.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/oneOf.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/allOf.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/if.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/thenElse.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/format.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input

**Comment by LokerL** [comment]
貌似只能等待微软那边的服务器正常
