### ISSUE TITLE
[Bug] 创建webscoket连接...

### ISSUE THREAD

**Issue by NioYookerr** [LokerL/tts-vue#72]
#### Describe the bug
昨晚下载1.8.7，今天上午试用感觉不错，都是用200字以内段落测试的。下午处理好了txt文档准备批量处理，也就200个文档。
先批量试了10个txt文档，每个基本都不超过2000字，但只成功生成了5个mp3文件，之后再也无法使用，无论是“批量”还是“文本”。
查询日志和作者blog发现，问题出在“创建webscoket连接...”。关闭并退出梯子、使用绕过国内网站、全局梯子，都不行。
按作者此前对其他问题的回复，换了1.8.5，依然无法使用，无论是“批量”还是“文本”都仍然存在“创建webscoket连接...”问题。
软件现在完全用不了了，好遗憾。
期待作者有时间的话还请看看怎么回事，非常感谢！
不知哪个信息有用，以下是developer tools上的信息：

============控制台==========

index.dc1a0429.js:87 清空缓存中
index.dc1a0429.js:18 
    <speak xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts" xmlns:emo="http://www.w3.org/2009/10/emotionml" version="1.0" xml:lang="en-US">
        <voice name="zh-CN-XiaoxiaoNeural">
            <mstts:express-as   >
                <prosody rate="0%" pitch="0%">
                你好啊
今天天气怎么样?
                </prosody>
            </mstts:express-as>
        </voice>
    </speak>
    
index.dc1a0429.js:18 创建webscoket连接...
index.dc1a0429.js:18 B3437F81EFC5495EA33A8CC930E6F743
2node:events:504 Uncaught Error: Invalid handshake: invalid first line format
    at Connection.checkHandshake (D:\soft\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:375:22)
    at Connection.readHandshake (D:\soft\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:331:54)
    at Connection.doRead (D:\soft\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:246:13)
    at TLSSocket.<anonymous> (D:\soft\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:66:8)
    at TLSSocket.emit (node:events:526:28)
    at emitReadable_ (node:internal/streams/readable:578:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/ajv.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/core.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/boolSchema.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/errors.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/code.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/scope.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/util.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/names.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/dataType.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/rules.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/applicability.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/defaults.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/keyword.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/code.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/subschema.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/resolve.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/validation_error.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/ref_error.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/uri.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/uri.all.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/draft7.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/id.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/ref.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/limitNumber.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/multipleOf.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/limitLength.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/ucs2length.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/pattern.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/limitProperties.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/required.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/limitItems.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/uniqueItems.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/equal.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/const.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/enum.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/additionalItems.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/prefixItems.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/items.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/items2020.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/contains.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/dependencies.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/propertyNames.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/additionalProperties.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/properties.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/patternProperties.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/not.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/anyOf.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/oneOf.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/allOf.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/if.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/thenElse.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/format.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/metadata.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/types.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/formats.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/limit.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/ajv.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/core.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/boolSchema.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/errors.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/code.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/scope.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/util.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/names.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/dataType.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/rules.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/applicability.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/defaults.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/keyword.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/code.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/subschema.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/resolve.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/validation_error.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/ref_error.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/uri.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/draft7.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/id.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/ref.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/limitNumber.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/multipleOf.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/limitLength.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/ucs2length.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/pattern.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/limitProperties.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/required.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/limitItems.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/uniqueItems.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/equal.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/const.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/enum.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/additionalItems.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/prefixItems.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/items.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/items2020.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/contains.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/dependencies.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/propertyNames.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/additionalProperties.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/properties.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/patternProperties.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/not.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/anyOf.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/oneOf.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/allOf.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/if.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/thenElse.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/format.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/metadata.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///D:/soft/tts-vue/resources/app.asar/dist/types.js.map 的内容：Unexpected end of JSON input

=========问题==========

Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.

受影响的资源
1 个来源
index.dc1a0429.js:1

**Comment by zspzip** [comment]
我的也是这个问题。

**Comment by LokerL** [comment]
按照以前的这种情况来说应该是微软那边的问题

**Comment by NioYookerr** [comment]
> 按照以前的这种情况来说应该是微软那边的问题

刚又试了一下，只转一篇文档就成功了。估计是不能一次转太多吧。
嗯，要是微软那边的问题，作者应该也没办法改变。
azure搞起来真是很累，一晚上了到现在还提示文档的格式有误，但又不说哪里有误，不值得怎么改。
总之非常感谢作者！
