### ISSUE TITLE
转换文本失败，默认的文本（你好啊 今天天气怎么样?）也转换失败

### ISSUE THREAD

**Issue by AyinJohn** [LokerL/tts-vue#73]
建议软件界面设计一个区别于白色的边框，让我有更好的体验，优化转换文本的具体格式，为什么纯文本.txt的转换不能转换？

**Comment by AyinJohn** [comment]
建议设计一个转换倒计时，更加直观一些。

**Comment by dashumeiyoumu** [comment]
不能转换指的是 转换后一直是汪汪汪的声音吗？有个tts的帮助网址说的是必须得是utf-8 bom的编码

**Comment by LokerL** [comment]
内容有特殊的字符就无法被识别，可能前几百个字正常响应，后面特殊字符无法识别会导致卡住。

对于倒计时，没办法获取到数据总量，没法计算剩余时间。
