### ISSUE TITLE
整个软件用不了。

### ISSUE THREAD

**Issue by Awei097** [LokerL/tts-vue#75]
#### Describe the bug
﻿
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/ajv.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/core.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/boolSchema.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/errors.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/code.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/scope.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/util.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/dataType.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/rules.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/applicability.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/defaults.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/keyword.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/code.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/subschema.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/resolve.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/validation_error.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/ref_error.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/uri.all.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/id.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/ref.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/limitNumber.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/multipleOf.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/limitLength.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/ucs2length.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/pattern.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/limitProperties.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/required.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/limitItems.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/uniqueItems.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/const.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/enum.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/additionalItems.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/prefixItems.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/items.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/items2020.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/contains.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/dependencies.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/propertyNames.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/additionalProperties.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/properties.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/patternProperties.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/not.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/oneOf.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///C:/Program%20Files/tts-vue/resources/app.asar/dist/allOf.js.map 的内容：Unexpected end of JSON input

**Comment by LokerL** [comment]
可以贴一下你的配置文件内容吗？
一般位置为：C:\Users\用户\AppData\Roaming\tts-vue\config.json

**Comment by lemonxiake** [comment]
同样的问题

**Comment by SSYLwn** [comment]
Uncaught Error: Invalid handshake: invalid first line format
    at Connection.checkHandshake (D:\牛学长\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:375:22)
    at Connection.readHandshake (D:\牛学长\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:331:54)
    at Connection.doRead (D:\牛学长\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:246:13)
    at TLSSocket.<anonymous> (D:\牛学长\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:66:8)
    at TLSSocket.emit (node:events:526:28)
    at emitReadable_ (node:internal/streams/readable:578:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by longwule** [comment]
DevTools 无法加载来源映射：无法解析 file:///J:/ruanjian/AIyuyin/tts-vue/resources/app.asar/dist/metadata.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///J:/ruanjian/AIyuyin/tts-vue/resources/app.asar/dist/index.js.map 的内容：Unexpected end of JSON input
DevTools 无法加载来源映射：无法解析 file:///J:/ruanjian/AIyuyin/tts-vue/resources/app.asar/dist/types.js.map 的内容：Unexpected end of JSON input
index.dc1a0429.js:18 
    <speak xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts" xmlns:emo="http://www.w3.org/2009/10/emotionml" version="1.0" xml:lang="en-US">
        <voice name="zh-CN-XiaoxiaoNeural">
            <mstts:express-as   >
                <prosody rate="0%" pitch="0%">
                如果你觉得这个项目还不错， 欢迎Star、Fork和PR。你的Star是对作者最好的鼓励。
                </prosody>
            </mstts:express-as>
        </voice>
    </speak>
    
index.dc1a0429.js:18 创建webscoket连接...
index.dc1a0429.js:18 036C6B4813AE4DA49762F11AD9D8A103
2node:events:504 Uncaught Error: Invalid handshake: invalid first line format
    at Connection.checkHandshake (J:\ruanjian\AIyuyin\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:375:22)
    at Connection.readHandshake (J:\ruanjian\AIyuyin\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:331:54)
    at Connection.doRead (J:\ruanjian\AIyuyin\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:246:13)
    at TLSSocket.<anonymous> (J:\ruanjian\AIyuyin\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:66:8)
    at TLSSocket.emit (node:events:526:28)
    at emitReadable_ (node:internal/streams/readable:578:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Connection.checkHandshake @ J:\ruanjian\AIyuyin\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:375
Connection.readHandshake @ J:\ruanjian\AIyuyin\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:331
Connection.doRead @ J:\ruanjian\AIyuyin\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:246
（匿名） @ J:\ruanjian\AIyuyin\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:66
emit @ node:events:526
emitReadable_ @ node:internal/streams/readable:578
processTicksAndRejections @ node:internal/process/task_queues:82
