### ISSUE TITLE
[Help] websocket连接咋那么不稳定呢

### ISSUE THREAD

**Issue by a997282418** [LokerL/tts-vue#79]
用宽带不行，用移动网合成了四五个就也不行了，大佬咋回事呀

**Comment by LokerL** [comment]
试试最新版，再不行的画我暂时没有想到其他解决方案了。或者可以尝试使用其他同类作软件。

PS:
对于网络问题，我觉得这并不是软件问题造成的，也许是我技术不到位，找不到其他的原因。
猜测现在的问题是连接不上微软的服务器，属于网络问题。解决方案嘛，就像你给别人打电话，没人接听，要去找人去修电话吗？
从客户端角度，我还暂时想不到解决方案，但是我也会有空去搜索学习其他开发者的解决思路（如果有的话）。如果找到了可行的解决方 案，我会及时更新到软件上的。
对于拙作在使用过程中的不便，个人技术问题还请见谅。

我更希望你可以同时去找找其他的同类软件或程序，佛系一点，没必要花个 1 分钱喷我一下，毕竟你下载和使用过程中是完全免费的。

如果找到了很稳定且免费的软件，也可以告知我，我也好去学习下经验。
