### ISSUE TITLE
能否添加一个自定义key 的接口

### ISSUE THREAD

**Issue by aiastia** [LokerL/tts-vue#8]
#### Describe the problem you confuse
能否添加一个自定义key 的接口
 搞了个azure 订阅……

**Comment by LokerL** [comment]
可以，下个版本吧。但是我觉得这个功能用到的不会很多。

**Comment by LokerL** [comment]
已更新相应功能。可以下载1.7.0或者Actions里面自动构建的1.7.1版本查看。
> 添加自定义的AuthToken，因为使用这个功能的可能不多，没把这个配置写到 UI 里面。需要在设置页面打开配置文件手动填写。

注意，这是个未经测试的功能更新，要是有问题请及时反馈。

**Comment by aiastia** [comment]
微软还要输入 **region **

https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/long-audio-api

**Comment by LokerL** [comment]
删除了相关的更新说明，我再测试测试吧，这个功能有可能被放弃。
