### ISSUE TITLE
[Bug] 下载路径不兼容mac系统

### ISSUE THREAD

**Issue by lephones** [LokerL/tts-vue#85]
src/global/initLocalStore.ts
里面的desktop路径使用了\\分割符，在mac中的下载路径就变成 User/xxx\DeskTop\/timestam.mp3
试试使用
const desktopDir = `${homeDir}/Desktop`。
我没有windows电脑，就没试。在windows下不行的话，也得使用path.join了。

**Comment by Cubik65536** [comment]
我创建了一个跨平台分支，merge 了本 repo 关于跨平台保存路径的修复的 pr，如果需要的话可以使用： https://github.com/CubikTech/tts-vue-multiplatform

如有问题可以在分支仓库的 issue 里提交反馈

**Comment by LokerL** [comment]
我没有MAC，很多地方没有做mac的适配
可以试试const desktopDir = require("path").resolve(homeDir, "Desktop");
