### ISSUE TITLE
能不能加个窗口最大化啊？

### ISSUE THREAD

**Issue by yzh979** [LokerL/tts-vue#9]
您好，能不能加个窗口最大化啊，我只想愉快的边看边听txt的内容，当个简易的txt内容阅读器。找过同类的产品也没有窗口最大化。为啥呢，都没这个需求吗？

**Comment by LokerL** [comment]
设计之初就没考虑响应式，所以很多宽高都是些死的。

**Comment by LokerL** [comment]
已更新响应式功能，支持最大最小化、任意改变窗口大小。可以下载1.7.0或者Actions里面自动构建的1.7.1版本查看。
