### ISSUE TITLE
小小的建议

### ISSUE THREAD

**Issue by Boss-Bai** [LokerL/tts-vue#95]
![image](https://user-images.githubusercontent.com/45356857/228248633-e0540101-7fbf-4ee2-ae91-7481c6c7c6b2.png)
我觉得如果个别地区在使用自身网络有问题时，可以在客户端有个地方能添加一个连接本地10808端口的设置。就能使用个人的魔法进行转语音。

**Comment by muxiazi** [comment]
你这个建议，我觉得可行，那我可就等了啊

**Comment by LokerL** [comment]
建议很好，但是没空搞哇
