### ISSUE TITLE
[Help] the title of help wanted report

### ISSUE THREAD

**Issue by wanox** [LokerL/tts-vue#98]
#### Describe the problem you confuse
今天就用不了啦，一直转圈圈，卸载了重新安装更新了也不行

**Comment by randerswan** [comment]
我这边也一样，应该是微软禁用了接口。

**Comment by wanox** [comment]
你好，邮件已收到 。我会尽快给你回复。

**Comment by LokerL** [comment]
微软好像关闭了免费的接口

**Comment by LokerL** [comment]
源代码已更新。预计2小时后上线安装包。版本号1.9.0。 @randerswan @wanox
