### ISSUE TITLE
[Help] 无法试听语音，转换文本点击后也显示一直在转换中没有反应

### ISSUE THREAD

**Issue by OldZhang5511** [LokerL/tts-vue#99]

**Comment by randerswan** [comment]
今天已经好几条Issues，估计微软今天封了接口，或者接口故障。前段时间网页版的试用窗口被隐藏，估计是封接口了。

**Comment by 1135890950** [comment]
应该是彻底不能用了

**Comment by ruanchao66** [comment]
一直在创建webscoket连接...，难受

**Comment by LokerL** [comment]
微软好像关闭了免费的接口

**Comment by fujiawei-dev** [comment]
> 大家有啥临时plan B分享一下吗

https://github.com/rany2/edge-tts 这个可以用

**Comment by debbiefu** [comment]
> > 大家有啥临时plan B分享一下吗
> 
> https://github.com/rany2/edge-tts 这个可以用

感谢！

**Comment by gzsxxny** [comment]
> > > 大家有啥临时plan B分享一下吗
> > 
> > 
> > https://github.com/rany2/edge-tts 这个可以用
> 
> 感谢！

请问要怎么用，求助，大佬 @ooMountain

**Comment by ooMountain** [comment]
> > > > 大家有啥临时plan B分享一下吗
> > > 
> > > 
> > > https://github.com/rany2/edge-tts 这个可以用
> > 
> > 
> > 感谢！
> 
> 请问要怎么用，求助，大佬 @ooMountain

耐心一点 按照教程的流程走下来 不难的 又找回我的云健了

**Comment by LokerL** [comment]
源代码已更新。预计2小时后上线安装包。版本号1.9.0。 @ooMountain @debbiefu @randerswan @fujiawei-dev @
